version: '3'
services:
  nginx:
    build: requirements/nginx/.
    image: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    restart: always
  
  mariadb:
    build: requirements/mariadb/.
    image: mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    restart: always

  wordpress:
    build: requirements/wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    restart: always
    env_file:
      - .env

networks:
  inception:

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/baki/Desktop/bkhatib/data/wordpress
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/baki/Desktop/bkhatib/data/mariadb